name=input("What is your name?: ")
age=input("How old are you?: ")
Age=int(age)
print("Hello",name,Age)
address=input("Where do you come from?: ")
current_year=input("what is the current year?: ")
Current_year=int(current_year)
born_year=int(Current_year-Age)
Born_year=int(born_year)
print("The year you were born is",Born_year)
